#!/bin/bash

if [ ! $DARKNET_DATA ] || [ ! $DARKNET_CFG ] || [ ! $DARKNET_WEIGHTS ]; then
    source args/darknet19_448.classify_args
fi

if [ ! $1 ]; then
    echo 'specify the top predicting object class'
    exit 1
fi

if [ ! $2 ]; then
    echo 'specify image(s)'
    exit 1
fi

COMMAND="./predict_classifier_multi $DARKNET_DATA $DARKNET_CFG $DARKNET_WEIGHTS $1 "

while [ $2 ]; do
    COMMAND="$COMMAND $2 "
    shift
done

echo $COMMAND

eval $COMMAND
